main: com.cavetale.signspy.SignSpyPlugin
name: SignSpy

version: 0.1
api-version: '1.20'

description: Spy on Signs
author: StarTux
website: https://github.com/StarTux/Chat

depend: [Chat]
softdepend: []

commands:
  signspy:
    aliases: []
    description: SignSpy Command
    permission: signspy.signspy
    usage: /signspy - Toggle sign spying

permissions:

  signspy.signspy:
    description: See sign edits and use /signspy
    default: false

  signspy.privacy:
    description: Be hidden from signspy
    default: op